spring:
  r2dbc:
    url: r2dbc:h2:file://F://Giacomo//monclick//database;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  data:
    rest:
      detection-strategy: visibility